INSERT INTO cityinfo VALUES ('0555','Scanning');
INSERT INTO CityInfo VALUES ('0800','Høje Taastrup');
INSERT INTO CityInfo VALUES ('0877','København C');
INSERT INTO CityInfo VALUES ('0892','Sjælland USF P');
INSERT INTO CityInfo VALUES ('0893','Sjælland USF B');
INSERT INTO CityInfo VALUES ('0894','Udbetaling');
INSERT INTO CityInfo VALUES ('0897','Brevsprækken');
INSERT INTO CityInfo VALUES ('0899','Kommuneservice');
INSERT INTO CityInfo VALUES ('0900','København C');
INSERT INTO CityInfo VALUES ('0910','København C');
INSERT INTO CityInfo VALUES ('0917','Københavns Pakkecenter');
INSERT INTO CityInfo VALUES ('0918','Københavns Pakke BRC');
INSERT INTO CityInfo VALUES ('0919','Returprint BRC');
INSERT INTO CityInfo VALUES ('0929','København C');
INSERT INTO CityInfo VALUES ('0960','Internationalt Postcenter');
INSERT INTO CityInfo VALUES ('0999','København C');
INSERT INTO CityInfo VALUES ('1000','København K');
INSERT INTO CityInfo VALUES ('1001','København K');
INSERT INTO CityInfo VALUES ('1002','København K');
INSERT INTO CityInfo VALUES ('1003','København K');
INSERT INTO CityInfo VALUES ('1004','København K');
INSERT INTO CityInfo VALUES ('1005','København K');
INSERT INTO CityInfo VALUES ('1006','København K');
INSERT INTO CityInfo VALUES ('1007','København K');
INSERT INTO CityInfo VALUES ('1008','København K');
INSERT INTO CityInfo VALUES ('1009','København K');
INSERT INTO CityInfo VALUES ('1010','København K');
INSERT INTO CityInfo VALUES ('1011','København K');
INSERT INTO CityInfo VALUES ('1012','København K');
INSERT INTO CityInfo VALUES ('1013','København K');
INSERT INTO CityInfo VALUES ('1014','København K');
INSERT INTO CityInfo VALUES ('1015','København K');
INSERT INTO CityInfo VALUES ('1016','København K');
INSERT INTO CityInfo VALUES ('1017','København K');
INSERT INTO CityInfo VALUES ('1018','København K');
INSERT INTO CityInfo VALUES ('1019','København K');
INSERT INTO CityInfo VALUES ('1020','København K');
INSERT INTO CityInfo VALUES ('1021','København K');
INSERT INTO CityInfo VALUES ('1022','København K');
INSERT INTO CityInfo VALUES ('1023','København K');
INSERT INTO CityInfo VALUES ('1024','København K');
INSERT INTO CityInfo VALUES ('1025','København K');
INSERT INTO CityInfo VALUES ('1026','København K');
INSERT INTO CityInfo VALUES ('1045','København K');
INSERT INTO CityInfo VALUES ('1050','København K');
INSERT INTO CityInfo VALUES ('1051','København K');
INSERT INTO CityInfo VALUES ('1052','København K');
INSERT INTO CityInfo VALUES ('1053','København K');
INSERT INTO CityInfo VALUES ('1054','København K');
INSERT INTO CityInfo VALUES ('1055','København K');
INSERT INTO CityInfo VALUES ('1056','København K');
INSERT INTO CityInfo VALUES ('1057','København K');
INSERT INTO CityInfo VALUES ('1058','København K');
INSERT INTO CityInfo VALUES ('1059','København K');
INSERT INTO CityInfo VALUES ('1060','København K');
INSERT INTO CityInfo VALUES ('1061','København K');
INSERT INTO CityInfo VALUES ('1062','København K');
INSERT INTO CityInfo VALUES ('1063','København K');
INSERT INTO CityInfo VALUES ('1064','København K');
INSERT INTO CityInfo VALUES ('1065','København K');
INSERT INTO CityInfo VALUES ('1066','København K');
INSERT INTO CityInfo VALUES ('1067','København K');
INSERT INTO CityInfo VALUES ('1068','København K');
INSERT INTO CityInfo VALUES ('1069','København K');
INSERT INTO CityInfo VALUES ('1070','København K');
INSERT INTO CityInfo VALUES ('1071','København K');
INSERT INTO CityInfo VALUES ('1072','København K');
INSERT INTO CityInfo VALUES ('1073','København K');
INSERT INTO CityInfo VALUES ('1074','København K');
INSERT INTO CityInfo VALUES ('1092','København K');
INSERT INTO CityInfo VALUES ('1093','København K');
INSERT INTO CityInfo VALUES ('1095','København K');
INSERT INTO CityInfo VALUES ('1098','København K');
INSERT INTO CityInfo VALUES ('1100','København K');
INSERT INTO CityInfo VALUES ('1101','København K');
INSERT INTO CityInfo VALUES ('1102','København K');
INSERT INTO CityInfo VALUES ('1103','København K');
INSERT INTO CityInfo VALUES ('1104','København K');
INSERT INTO CityInfo VALUES ('1105','København K');
INSERT INTO CityInfo VALUES ('1106','København K');
INSERT INTO CityInfo VALUES ('1107','København K');
INSERT INTO CityInfo VALUES ('1110','København K');
INSERT INTO CityInfo VALUES ('1111','København K');
INSERT INTO CityInfo VALUES ('1112','København K');
INSERT INTO CityInfo VALUES ('1113','København K');
INSERT INTO CityInfo VALUES ('1114','København K');
INSERT INTO CityInfo VALUES ('1115','København K');
INSERT INTO CityInfo VALUES ('1116','København K');
INSERT INTO CityInfo VALUES ('1117','København K');
INSERT INTO CityInfo VALUES ('1118','København K');
INSERT INTO CityInfo VALUES ('1119','København K');
INSERT INTO CityInfo VALUES ('1120','København K');
INSERT INTO CityInfo VALUES ('1121','København K');
INSERT INTO CityInfo VALUES ('1122','København K');
INSERT INTO CityInfo VALUES ('1123','København K');
INSERT INTO CityInfo VALUES ('1124','København K');
INSERT INTO CityInfo VALUES ('1125','København K');
INSERT INTO CityInfo VALUES ('1126','København K');
INSERT INTO CityInfo VALUES ('1127','København K');
INSERT INTO CityInfo VALUES ('1128','København K');
INSERT INTO CityInfo VALUES ('1129','København K');
INSERT INTO CityInfo VALUES ('1130','København K');
INSERT INTO CityInfo VALUES ('1131','København K');
INSERT INTO CityInfo VALUES ('1140','København K');
INSERT INTO CityInfo VALUES ('1147','København K');
INSERT INTO CityInfo VALUES ('1148','København K');
INSERT INTO CityInfo VALUES ('1150','København K');
INSERT INTO CityInfo VALUES ('1151','København K');
INSERT INTO CityInfo VALUES ('1152','København K');
INSERT INTO CityInfo VALUES ('1153','København K');
INSERT INTO CityInfo VALUES ('1154','København K');
INSERT INTO CityInfo VALUES ('1155','København K');
INSERT INTO CityInfo VALUES ('1156','København K');
INSERT INTO CityInfo VALUES ('1157','København K');
INSERT INTO CityInfo VALUES ('1158','København K');
INSERT INTO CityInfo VALUES ('1159','København K');
INSERT INTO CityInfo VALUES ('1160','København K');
INSERT INTO CityInfo VALUES ('1161','København K');
INSERT INTO CityInfo VALUES ('1162','København K');
INSERT INTO CityInfo VALUES ('1163','København K');
INSERT INTO CityInfo VALUES ('1164','København K');
INSERT INTO CityInfo VALUES ('1165','København K');
INSERT INTO CityInfo VALUES ('1166','København K');
INSERT INTO CityInfo VALUES ('1167','København K');
INSERT INTO CityInfo VALUES ('1168','København K');
INSERT INTO CityInfo VALUES ('1169','København K');
INSERT INTO CityInfo VALUES ('1170','København K');
INSERT INTO CityInfo VALUES ('1171','København K');
INSERT INTO CityInfo VALUES ('1172','København K');
INSERT INTO CityInfo VALUES ('1173','København K');
INSERT INTO CityInfo VALUES ('1174','København K');
INSERT INTO CityInfo VALUES ('1175','København K');
INSERT INTO CityInfo VALUES ('1200','København K');
INSERT INTO CityInfo VALUES ('1201','København K');
INSERT INTO CityInfo VALUES ('1202','København K');
INSERT INTO CityInfo VALUES ('1203','København K');
INSERT INTO CityInfo VALUES ('1204','København K');
INSERT INTO CityInfo VALUES ('1205','København K');
INSERT INTO CityInfo VALUES ('1206','København K');
INSERT INTO CityInfo VALUES ('1207','København K');
INSERT INTO CityInfo VALUES ('1208','København K');
INSERT INTO CityInfo VALUES ('1209','København K');
INSERT INTO CityInfo VALUES ('1210','København K');
INSERT INTO CityInfo VALUES ('1211','København K');
INSERT INTO CityInfo VALUES ('1212','København K');
INSERT INTO CityInfo VALUES ('1213','København K');
INSERT INTO CityInfo VALUES ('1214','København K');
INSERT INTO CityInfo VALUES ('1215','København K');
INSERT INTO CityInfo VALUES ('1216','København K');
INSERT INTO CityInfo VALUES ('1217','København K');
INSERT INTO CityInfo VALUES ('1218','København K');
INSERT INTO CityInfo VALUES ('1219','København K');
INSERT INTO CityInfo VALUES ('1220','København K');
INSERT INTO CityInfo VALUES ('1221','København K');
INSERT INTO CityInfo VALUES ('1240','København K');
INSERT INTO CityInfo VALUES ('1250','København K');
INSERT INTO CityInfo VALUES ('1251','København K');
INSERT INTO CityInfo VALUES ('1252','København K');
INSERT INTO CityInfo VALUES ('1253','København K');
INSERT INTO CityInfo VALUES ('1254','København K');
INSERT INTO CityInfo VALUES ('1255','København K');
INSERT INTO CityInfo VALUES ('1256','København K');
INSERT INTO CityInfo VALUES ('1257','København K');
INSERT INTO CityInfo VALUES ('1258','København K');
INSERT INTO CityInfo VALUES ('1259','København K');
INSERT INTO CityInfo VALUES ('1260','København K');
INSERT INTO CityInfo VALUES ('1261','København K');
INSERT INTO CityInfo VALUES ('1263','København K');
INSERT INTO CityInfo VALUES ('1264','København K');
INSERT INTO CityInfo VALUES ('1265','København K');
INSERT INTO CityInfo VALUES ('1266','København K');
INSERT INTO CityInfo VALUES ('1267','København K');
INSERT INTO CityInfo VALUES ('1268','København K');
INSERT INTO CityInfo VALUES ('1270','København K');
INSERT INTO CityInfo VALUES ('1271','København K');
INSERT INTO CityInfo VALUES ('1291','København K');
INSERT INTO CityInfo VALUES ('1300','København K');
INSERT INTO CityInfo VALUES ('1301','København K');
INSERT INTO CityInfo VALUES ('1302','København K');
INSERT INTO CityInfo VALUES ('1303','København K');
INSERT INTO CityInfo VALUES ('1304','København K');
INSERT INTO CityInfo VALUES ('1306','København K');
INSERT INTO CityInfo VALUES ('1307','København K');
INSERT INTO CityInfo VALUES ('1308','København K');
INSERT INTO CityInfo VALUES ('1309','København K');
INSERT INTO CityInfo VALUES ('1310','København K');
INSERT INTO CityInfo VALUES ('1311','København K');
INSERT INTO CityInfo VALUES ('1312','København K');
INSERT INTO CityInfo VALUES ('1313','København K');
INSERT INTO CityInfo VALUES ('1314','København K');
INSERT INTO CityInfo VALUES ('1315','København K');
INSERT INTO CityInfo VALUES ('1316','København K');
INSERT INTO CityInfo VALUES ('1317','København K');
INSERT INTO CityInfo VALUES ('1318','København K');
INSERT INTO CityInfo VALUES ('1319','København K');
INSERT INTO CityInfo VALUES ('1320','København K');
INSERT INTO CityInfo VALUES ('1321','København K');
INSERT INTO CityInfo VALUES ('1322','København K');
INSERT INTO CityInfo VALUES ('1323','København K');
INSERT INTO CityInfo VALUES ('1324','København K');
INSERT INTO CityInfo VALUES ('1325','København K');
INSERT INTO CityInfo VALUES ('1326','København K');
INSERT INTO CityInfo VALUES ('1327','København K');
INSERT INTO CityInfo VALUES ('1328','København K');
INSERT INTO CityInfo VALUES ('1329','København K');
INSERT INTO CityInfo VALUES ('1350','København K');
INSERT INTO CityInfo VALUES ('1352','København K');
INSERT INTO CityInfo VALUES ('1353','København K');
INSERT INTO CityInfo VALUES ('1354','København K');
INSERT INTO CityInfo VALUES ('1355','København K');
INSERT INTO CityInfo VALUES ('1356','København K');
INSERT INTO CityInfo VALUES ('1357','København K');
INSERT INTO CityInfo VALUES ('1358','København K');
INSERT INTO CityInfo VALUES ('1359','København K');
INSERT INTO CityInfo VALUES ('1360','København K');
INSERT INTO CityInfo VALUES ('1361','København K');
INSERT INTO CityInfo VALUES ('1362','København K');
INSERT INTO CityInfo VALUES ('1363','København K');
INSERT INTO CityInfo VALUES ('1364','København K');
INSERT INTO CityInfo VALUES ('1365','København K');
INSERT INTO CityInfo VALUES ('1366','København K');
INSERT INTO CityInfo VALUES ('1367','København K');
INSERT INTO CityInfo VALUES ('1368','København K');
INSERT INTO CityInfo VALUES ('1369','København K');
INSERT INTO CityInfo VALUES ('1370','København K');
INSERT INTO CityInfo VALUES ('1371','København K');
INSERT INTO CityInfo VALUES ('1400','København K');
INSERT INTO CityInfo VALUES ('1401','København K');
INSERT INTO CityInfo VALUES ('1402','København K');
INSERT INTO CityInfo VALUES ('1403','København K');
INSERT INTO CityInfo VALUES ('1404','København K');
INSERT INTO CityInfo VALUES ('1406','København K');
INSERT INTO CityInfo VALUES ('1407','København K');
INSERT INTO CityInfo VALUES ('1408','København K');
INSERT INTO CityInfo VALUES ('1409','København K');
INSERT INTO CityInfo VALUES ('1410','København K');
INSERT INTO CityInfo VALUES ('1411','København K');
INSERT INTO CityInfo VALUES ('1412','København K');
INSERT INTO CityInfo VALUES ('1413','København K');
INSERT INTO CityInfo VALUES ('1414','København K');
INSERT INTO CityInfo VALUES ('1415','København K');
INSERT INTO CityInfo VALUES ('1416','København K');
INSERT INTO CityInfo VALUES ('1417','København K');
INSERT INTO CityInfo VALUES ('1418','København K');
INSERT INTO CityInfo VALUES ('1419','København K');
INSERT INTO CityInfo VALUES ('1420','København K');
INSERT INTO CityInfo VALUES ('1421','København K');
INSERT INTO CityInfo VALUES ('1422','København K');
INSERT INTO CityInfo VALUES ('1423','København K');
INSERT INTO CityInfo VALUES ('1424','København K');
INSERT INTO CityInfo VALUES ('1425','København K');
INSERT INTO CityInfo VALUES ('1426','København K');
INSERT INTO CityInfo VALUES ('1427','København K');
INSERT INTO CityInfo VALUES ('1428','København K');
INSERT INTO CityInfo VALUES ('1429','København K');
INSERT INTO CityInfo VALUES ('1430','København K');
INSERT INTO CityInfo VALUES ('1431','København K');
INSERT INTO CityInfo VALUES ('1432','København K');
INSERT INTO CityInfo VALUES ('1433','København K');
INSERT INTO CityInfo VALUES ('1434','København K');
INSERT INTO CityInfo VALUES ('1435','København K');
INSERT INTO CityInfo VALUES ('1436','København K');
INSERT INTO CityInfo VALUES ('1437','København K');
INSERT INTO CityInfo VALUES ('1438','København K');
INSERT INTO CityInfo VALUES ('1439','København K');
INSERT INTO CityInfo VALUES ('1440','København K');
INSERT INTO CityInfo VALUES ('1441','København K');
INSERT INTO CityInfo VALUES ('1448','København K');
INSERT INTO CityInfo VALUES ('1450','København K');
INSERT INTO CityInfo VALUES ('1452','København K');
INSERT INTO CityInfo VALUES ('1453','København K');
INSERT INTO CityInfo VALUES ('1454','København K');
INSERT INTO CityInfo VALUES ('1455','København K');
INSERT INTO CityInfo VALUES ('1456','København K');
INSERT INTO CityInfo VALUES ('1457','København K');
INSERT INTO CityInfo VALUES ('1458','København K');
INSERT INTO CityInfo VALUES ('1459','København K');
INSERT INTO CityInfo VALUES ('1460','København K');
INSERT INTO CityInfo VALUES ('1461','København K');
INSERT INTO CityInfo VALUES ('1462','København K');
INSERT INTO CityInfo VALUES ('1463','København K');
INSERT INTO CityInfo VALUES ('1464','København K');
INSERT INTO CityInfo VALUES ('1465','København K');
INSERT INTO CityInfo VALUES ('1466','København K');
INSERT INTO CityInfo VALUES ('1467','København K');
INSERT INTO CityInfo VALUES ('1468','København K');
INSERT INTO CityInfo VALUES ('1470','København K');
INSERT INTO CityInfo VALUES ('1471','København K');
INSERT INTO CityInfo VALUES ('1472','København K');
INSERT INTO CityInfo VALUES ('1473','København K');
INSERT INTO CityInfo VALUES ('1500','København V');
INSERT INTO CityInfo VALUES ('1501','København V');
INSERT INTO CityInfo VALUES ('1502','København V');
INSERT INTO CityInfo VALUES ('1503','København V');
INSERT INTO CityInfo VALUES ('1504','København V');
INSERT INTO CityInfo VALUES ('1505','København V');
INSERT INTO CityInfo VALUES ('1506','København V');
INSERT INTO CityInfo VALUES ('1507','København V');
INSERT INTO CityInfo VALUES ('1508','København V');
INSERT INTO CityInfo VALUES ('1509','København V');
INSERT INTO CityInfo VALUES ('1510','København V');
INSERT INTO CityInfo VALUES ('1512','Returpost');
INSERT INTO CityInfo VALUES ('1513','Centraltastning');
INSERT INTO CityInfo VALUES ('1532','København V');
INSERT INTO CityInfo VALUES ('1533','København V');
INSERT INTO CityInfo VALUES ('1550','København V');
INSERT INTO CityInfo VALUES ('1551','København V');
INSERT INTO CityInfo VALUES ('1552','København V');
INSERT INTO CityInfo VALUES ('1553','København V');
INSERT INTO CityInfo VALUES ('1554','København V');
INSERT INTO CityInfo VALUES ('1555','København V');
INSERT INTO CityInfo VALUES ('1556','København V');
INSERT INTO CityInfo VALUES ('1557','København V');
INSERT INTO CityInfo VALUES ('1558','København V');
INSERT INTO CityInfo VALUES ('1559','København V');
INSERT INTO CityInfo VALUES ('1560','København V');
INSERT INTO CityInfo VALUES ('1561','København V');
INSERT INTO CityInfo VALUES ('1562','København V');
INSERT INTO CityInfo VALUES ('1563','København V');
INSERT INTO CityInfo VALUES ('1564','København V');
INSERT INTO CityInfo VALUES ('1566','København V');
INSERT INTO CityInfo VALUES ('1567','København V');
INSERT INTO CityInfo VALUES ('1568','København V');
INSERT INTO CityInfo VALUES ('1569','København V');
INSERT INTO CityInfo VALUES ('1570','København V');
INSERT INTO CityInfo VALUES ('1571','København V');
INSERT INTO CityInfo VALUES ('1572','København V');
INSERT INTO CityInfo VALUES ('1573','København V');
INSERT INTO CityInfo VALUES ('1574','København V');
INSERT INTO CityInfo VALUES ('1575','København V');
INSERT INTO CityInfo VALUES ('1576','København V');
INSERT INTO CityInfo VALUES ('1577','København V');
INSERT INTO CityInfo VALUES ('1592','København V');
INSERT INTO CityInfo VALUES ('1599','København V');
INSERT INTO CityInfo VALUES ('1600','København V');
INSERT INTO CityInfo VALUES ('1601','København V');
INSERT INTO CityInfo VALUES ('1602','København V');
INSERT INTO CityInfo VALUES ('1603','København V');
INSERT INTO CityInfo VALUES ('1604','København V');
INSERT INTO CityInfo VALUES ('1605','København V');
INSERT INTO CityInfo VALUES ('1606','København V');
INSERT INTO CityInfo VALUES ('1607','København V');
INSERT INTO CityInfo VALUES ('1608','København V');
INSERT INTO CityInfo VALUES ('1609','København V');
INSERT INTO CityInfo VALUES ('1610','København V');
INSERT INTO CityInfo VALUES ('1611','København V');
INSERT INTO CityInfo VALUES ('1612','København V');
INSERT INTO CityInfo VALUES ('1613','København V');
INSERT INTO CityInfo VALUES ('1614','København V');
INSERT INTO CityInfo VALUES ('1615','København V');
INSERT INTO CityInfo VALUES ('1616','København V');
INSERT INTO CityInfo VALUES ('1617','København V');
INSERT INTO CityInfo VALUES ('1618','København V');
INSERT INTO CityInfo VALUES ('1619','København V');
INSERT INTO CityInfo VALUES ('1620','København V');
INSERT INTO CityInfo VALUES ('1621','København V');
INSERT INTO CityInfo VALUES ('1622','København V');
INSERT INTO CityInfo VALUES ('1623','København V');
INSERT INTO CityInfo VALUES ('1624','København V');
INSERT INTO CityInfo VALUES ('1630','København V');
INSERT INTO CityInfo VALUES ('1631','København V');
INSERT INTO CityInfo VALUES ('1632','København V');
INSERT INTO CityInfo VALUES ('1633','København V');
INSERT INTO CityInfo VALUES ('1634','København V');
INSERT INTO CityInfo VALUES ('1635','København V');
INSERT INTO CityInfo VALUES ('1650','København V');
INSERT INTO CityInfo VALUES ('1651','København V');
INSERT INTO CityInfo VALUES ('1652','København V');
INSERT INTO CityInfo VALUES ('1653','København V');
INSERT INTO CityInfo VALUES ('1654','København V');
INSERT INTO CityInfo VALUES ('1655','København V');
INSERT INTO CityInfo VALUES ('1656','København V');
INSERT INTO CityInfo VALUES ('1657','København V');
INSERT INTO CityInfo VALUES ('1658','København V');
INSERT INTO CityInfo VALUES ('1659','København V');
INSERT INTO CityInfo VALUES ('1660','København V');
INSERT INTO CityInfo VALUES ('1661','København V');
INSERT INTO CityInfo VALUES ('1662','København V');
INSERT INTO CityInfo VALUES ('1663','København V');
INSERT INTO CityInfo VALUES ('1664','København V');
INSERT INTO CityInfo VALUES ('1665','København V');
INSERT INTO CityInfo VALUES ('1666','København V');
INSERT INTO CityInfo VALUES ('1667','København V');
INSERT INTO CityInfo VALUES ('1668','København V');
INSERT INTO CityInfo VALUES ('1669','København V');
INSERT INTO CityInfo VALUES ('1670','København V');
INSERT INTO CityInfo VALUES ('1671','København V');
INSERT INTO CityInfo VALUES ('1672','København V');
INSERT INTO CityInfo VALUES ('1673','København V');
INSERT INTO CityInfo VALUES ('1674','København V');
INSERT INTO CityInfo VALUES ('1675','København V');
INSERT INTO CityInfo VALUES ('1676','København V');
INSERT INTO CityInfo VALUES ('1677','København V');
INSERT INTO CityInfo VALUES ('1699','København V');
INSERT INTO CityInfo VALUES ('1700','København V');
INSERT INTO CityInfo VALUES ('1701','København V');
INSERT INTO CityInfo VALUES ('1702','København V');
INSERT INTO CityInfo VALUES ('1703','København V');
INSERT INTO CityInfo VALUES ('1704','København V');
INSERT INTO CityInfo VALUES ('1705','København V');
INSERT INTO CityInfo VALUES ('1706','København V');
INSERT INTO CityInfo VALUES ('1707','København V');
INSERT INTO CityInfo VALUES ('1708','København V');
INSERT INTO CityInfo VALUES ('1709','København V');
INSERT INTO CityInfo VALUES ('1710','København V');
INSERT INTO CityInfo VALUES ('1711','København V');
INSERT INTO CityInfo VALUES ('1712','København V');
INSERT INTO CityInfo VALUES ('1713','København V');
INSERT INTO CityInfo VALUES ('1714','København V');
INSERT INTO CityInfo VALUES ('1715','København V');
INSERT INTO CityInfo VALUES ('1716','København V');
INSERT INTO CityInfo VALUES ('1717','København V');
INSERT INTO CityInfo VALUES ('1718','København V');
INSERT INTO CityInfo VALUES ('1719','København V');
INSERT INTO CityInfo VALUES ('1720','København V');
INSERT INTO CityInfo VALUES ('1721','København V');
INSERT INTO CityInfo VALUES ('1722','København V');
INSERT INTO CityInfo VALUES ('1723','København V');
INSERT INTO CityInfo VALUES ('1724','København V');
INSERT INTO CityInfo VALUES ('1725','København V');
INSERT INTO CityInfo VALUES ('1726','København V');
INSERT INTO CityInfo VALUES ('1727','København V');
INSERT INTO CityInfo VALUES ('1728','København V');
INSERT INTO CityInfo VALUES ('1729','København V');
INSERT INTO CityInfo VALUES ('1730','København V');
INSERT INTO CityInfo VALUES ('1731','København V');
INSERT INTO CityInfo VALUES ('1732','København V');
INSERT INTO CityInfo VALUES ('1733','København V');
INSERT INTO CityInfo VALUES ('1734','København V');
INSERT INTO CityInfo VALUES ('1735','København V');
INSERT INTO CityInfo VALUES ('1736','København V');
INSERT INTO CityInfo VALUES ('1737','København V');
INSERT INTO CityInfo VALUES ('1738','København V');
INSERT INTO CityInfo VALUES ('1739','København V');
INSERT INTO CityInfo VALUES ('1749','København V');
INSERT INTO CityInfo VALUES ('1750','København V');
INSERT INTO CityInfo VALUES ('1751','København V');
INSERT INTO CityInfo VALUES ('1752','København V');
INSERT INTO CityInfo VALUES ('1753','København V');
INSERT INTO CityInfo VALUES ('1754','København V');
INSERT INTO CityInfo VALUES ('1755','København V');
INSERT INTO CityInfo VALUES ('1756','København V');
INSERT INTO CityInfo VALUES ('1757','København V');
INSERT INTO CityInfo VALUES ('1758','København V');
INSERT INTO CityInfo VALUES ('1759','København V');
INSERT INTO CityInfo VALUES ('1760','København V');
INSERT INTO CityInfo VALUES ('1761','København V');
INSERT INTO CityInfo VALUES ('1762','København V');
INSERT INTO CityInfo VALUES ('1763','København V');
INSERT INTO CityInfo VALUES ('1764','København V');
INSERT INTO CityInfo VALUES ('1765','København V');
INSERT INTO CityInfo VALUES ('1766','København V');
INSERT INTO CityInfo VALUES ('1770','København V');
INSERT INTO CityInfo VALUES ('1771','København V');
INSERT INTO CityInfo VALUES ('1772','København V');
INSERT INTO CityInfo VALUES ('1773','København V');
INSERT INTO CityInfo VALUES ('1774','København V');
INSERT INTO CityInfo VALUES ('1775','København V');
INSERT INTO CityInfo VALUES ('1777','København V');
INSERT INTO CityInfo VALUES ('1780','København V');
INSERT INTO CityInfo VALUES ('1782','København V');
INSERT INTO CityInfo VALUES ('1785','København V');
INSERT INTO CityInfo VALUES ('1786','København V');
INSERT INTO CityInfo VALUES ('1787','København V');
INSERT INTO CityInfo VALUES ('1790','København V');
INSERT INTO CityInfo VALUES ('1799','København V');
INSERT INTO CityInfo VALUES ('1800','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1801','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1802','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1803','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1804','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1805','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1806','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1807','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1808','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1809','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1810','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1811','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1812','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1813','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1814','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1815','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1816','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1817','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1818','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1819','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1820','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1822','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1823','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1824','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1825','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1826','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1827','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1828','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1829','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1835','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1850','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1851','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1852','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1853','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1854','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1855','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1856','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1857','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1860','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1861','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1862','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1863','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1864','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1865','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1866','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1867','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1868','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1870','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1871','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1872','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1873','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1874','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1875','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1876','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1877','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1878','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1879','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1900','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1901','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1902','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1903','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1904','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1905','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1906','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1908','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1909','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1910','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1911','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1912','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1913','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1914','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1915','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1916','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1917','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1920','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1921','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1922','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1923','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1924','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1925','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1926','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1927','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1928','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1931','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1950','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1951','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1952','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1953','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1954','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1955','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1956','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1957','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1958','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1959','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1960','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1961','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1962','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1963','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1964','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1965','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1966','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1967','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1970','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1971','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1972','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1973','Frederiksberg C');
INSERT INTO CityInfo VALUES ('1974','Frederiksberg C');
INSERT INTO CityInfo VALUES ('2000','Frederiksberg');
INSERT INTO CityInfo VALUES ('2100','København Ø');
INSERT INTO CityInfo VALUES ('2150','Nordhavn');
INSERT INTO CityInfo VALUES ('2200','København N');
INSERT INTO CityInfo VALUES ('2300','København S');
INSERT INTO CityInfo VALUES ('2400','København NV');
INSERT INTO CityInfo VALUES ('2450','København SV');
INSERT INTO CityInfo VALUES ('2500','Valby');
INSERT INTO CityInfo VALUES ('2600','Glostrup');
INSERT INTO CityInfo VALUES ('2605','Brøndby');
INSERT INTO CityInfo VALUES ('2610','Rødovre');
INSERT INTO CityInfo VALUES ('2620','Albertslund');
INSERT INTO CityInfo VALUES ('2625','Vallensbæk');
INSERT INTO CityInfo VALUES ('2630','Taastrup');
INSERT INTO CityInfo VALUES ('2635','Ishøj');
INSERT INTO CityInfo VALUES ('2640','Hedehusene');
INSERT INTO CityInfo VALUES ('2650','Hvidovre');
INSERT INTO CityInfo VALUES ('2660','Brøndby Strand');
INSERT INTO CityInfo VALUES ('2665','Vallensbæk Strand');
INSERT INTO CityInfo VALUES ('2670','Greve');
INSERT INTO CityInfo VALUES ('2680','Solrød Strand');
INSERT INTO CityInfo VALUES ('2690','Karlslunde');
INSERT INTO CityInfo VALUES ('2700','Brønshøj');
INSERT INTO CityInfo VALUES ('2720','Vanløse');
INSERT INTO CityInfo VALUES ('2730','Herlev');
INSERT INTO CityInfo VALUES ('2740','Skovlunde');
INSERT INTO CityInfo VALUES ('2750','Ballerup');
INSERT INTO CityInfo VALUES ('2760','Måløv');
INSERT INTO CityInfo VALUES ('2765','Smørum');
INSERT INTO CityInfo VALUES ('2770','Kastrup');
INSERT INTO CityInfo VALUES ('2791','Dragør');
INSERT INTO CityInfo VALUES ('2800','Kongens Lyngby');
INSERT INTO CityInfo VALUES ('2820','Gentofte');
INSERT INTO CityInfo VALUES ('2830','Virum');
INSERT INTO CityInfo VALUES ('2840','Holte');
INSERT INTO CityInfo VALUES ('2850','Nærum');
INSERT INTO CityInfo VALUES ('2860','Søborg');
INSERT INTO CityInfo VALUES ('2870','Dyssegård');
INSERT INTO CityInfo VALUES ('2880','Bagsværd');
INSERT INTO CityInfo VALUES ('2900','Hellerup');
INSERT INTO CityInfo VALUES ('2920','Charlottenlund');
INSERT INTO CityInfo VALUES ('2930','Klampenborg');
INSERT INTO CityInfo VALUES ('2942','Skodsborg');
INSERT INTO CityInfo VALUES ('2950','Vedbæk');
INSERT INTO CityInfo VALUES ('2960','Rungsted Kyst');
INSERT INTO CityInfo VALUES ('2970','Hørsholm');
INSERT INTO CityInfo VALUES ('2980','Kokkedal');
INSERT INTO CityInfo VALUES ('2990','Nivå');
INSERT INTO CityInfo VALUES ('3000','Helsingør');
INSERT INTO CityInfo VALUES ('3050','Humlebæk');
INSERT INTO CityInfo VALUES ('3060','Espergærde');
INSERT INTO CityInfo VALUES ('3070','Snekkersten');
INSERT INTO CityInfo VALUES ('3080','Tikøb');
INSERT INTO CityInfo VALUES ('3100','Hornbæk');
INSERT INTO CityInfo VALUES ('3120','Dronningmølle');
INSERT INTO CityInfo VALUES ('3140','Ålsgårde');
INSERT INTO CityInfo VALUES ('3150','Hellebæk');
INSERT INTO CityInfo VALUES ('3200','Helsinge');
INSERT INTO CityInfo VALUES ('3210','Vejby');
INSERT INTO CityInfo VALUES ('3220','Tisvildeleje');
INSERT INTO CityInfo VALUES ('3230','Græsted');
INSERT INTO CityInfo VALUES ('3250','Gilleleje');
INSERT INTO CityInfo VALUES ('3300','Frederiksværk');
INSERT INTO CityInfo VALUES ('3310','Ølsted');
INSERT INTO CityInfo VALUES ('3320','Skævinge');
INSERT INTO CityInfo VALUES ('3330','Gørløse');
INSERT INTO CityInfo VALUES ('3360','Liseleje');
INSERT INTO CityInfo VALUES ('3370','Melby');
INSERT INTO CityInfo VALUES ('3390','Hundested');
INSERT INTO CityInfo VALUES ('3400','Hillerød');
INSERT INTO CityInfo VALUES ('3450','Allerød');
INSERT INTO CityInfo VALUES ('3460','Birkerød');
INSERT INTO CityInfo VALUES ('3480','Fredensborg');
INSERT INTO CityInfo VALUES ('3490','Kvistgård');
INSERT INTO CityInfo VALUES ('3500','Værløse');
INSERT INTO CityInfo VALUES ('3520','Farum');
INSERT INTO CityInfo VALUES ('3540','Lynge');
INSERT INTO CityInfo VALUES ('3550','Slangerup');
INSERT INTO CityInfo VALUES ('3600','Frederikssund');
INSERT INTO CityInfo VALUES ('3630','Jægerspris');
INSERT INTO CityInfo VALUES ('3650','Ølstykke');
INSERT INTO CityInfo VALUES ('3660','Stenløse');
INSERT INTO CityInfo VALUES ('3670','Veksø Sjælland');
INSERT INTO CityInfo VALUES ('3700','Rønne');
INSERT INTO CityInfo VALUES ('3720','Aakirkeby');
INSERT INTO CityInfo VALUES ('3730','Nexø');
INSERT INTO CityInfo VALUES ('3740','Svaneke');
INSERT INTO CityInfo VALUES ('3751','Østermarie');
INSERT INTO CityInfo VALUES ('3760','Gudhjem');
INSERT INTO CityInfo VALUES ('3770','Allinge');
INSERT INTO CityInfo VALUES ('3782','Klemensker');
INSERT INTO CityInfo VALUES ('3790','Hasle');
INSERT INTO CityInfo VALUES ('4000','Roskilde');
INSERT INTO CityInfo VALUES ('4030','Tune');
INSERT INTO CityInfo VALUES ('4040','Jyllinge');
INSERT INTO CityInfo VALUES ('4050','Skibby');
INSERT INTO CityInfo VALUES ('4060','Kirke Såby');
INSERT INTO CityInfo VALUES ('4070','Kirke Hyllinge');
INSERT INTO CityInfo VALUES ('4100','Ringsted');
INSERT INTO CityInfo VALUES ('4129','Ringsted');
INSERT INTO CityInfo VALUES ('4130','Viby Sjælland');
INSERT INTO CityInfo VALUES ('4140','Borup');
INSERT INTO CityInfo VALUES ('4160','Herlufmagle');
INSERT INTO CityInfo VALUES ('4171','Glumsø');
INSERT INTO CityInfo VALUES ('4173','Fjenneslev');
INSERT INTO CityInfo VALUES ('4174','Jystrup Midtsj');
INSERT INTO CityInfo VALUES ('4180','Sorø');
INSERT INTO CityInfo VALUES ('4190','Munke Bjergby');
INSERT INTO CityInfo VALUES ('4200','Slagelse');
INSERT INTO CityInfo VALUES ('4220','Korsør');
INSERT INTO CityInfo VALUES ('4230','Skælskør');
INSERT INTO CityInfo VALUES ('4241','Vemmelev');
INSERT INTO CityInfo VALUES ('4242','Boeslunde');
INSERT INTO CityInfo VALUES ('4243','Rude');
INSERT INTO CityInfo VALUES ('4250','Fuglebjerg');
INSERT INTO CityInfo VALUES ('4261','Dalmose');
INSERT INTO CityInfo VALUES ('4262','Sandved');
INSERT INTO CityInfo VALUES ('4270','Høng');
INSERT INTO CityInfo VALUES ('4281','Gørlev');
INSERT INTO CityInfo VALUES ('4291','Ruds Vedby');
INSERT INTO CityInfo VALUES ('4293','Dianalund');
INSERT INTO CityInfo VALUES ('4295','Stenlille');
INSERT INTO CityInfo VALUES ('4296','Nyrup');
INSERT INTO CityInfo VALUES ('4300','Holbæk');
INSERT INTO CityInfo VALUES ('4320','Lejre');
INSERT INTO CityInfo VALUES ('4330','Hvalsø');
INSERT INTO CityInfo VALUES ('4340','Tølløse');
INSERT INTO CityInfo VALUES ('4350','Ugerløse');
INSERT INTO CityInfo VALUES ('4360','Kirke Eskilstrup');
INSERT INTO CityInfo VALUES ('4370','Store Merløse');
INSERT INTO CityInfo VALUES ('4390','Vipperød');
INSERT INTO CityInfo VALUES ('4400','Kalundborg');
INSERT INTO CityInfo VALUES ('4420','Regstrup');
INSERT INTO CityInfo VALUES ('4440','Mørkøv');
INSERT INTO CityInfo VALUES ('4450','Jyderup');
INSERT INTO CityInfo VALUES ('4460','Snertinge');
INSERT INTO CityInfo VALUES ('4470','Svebølle');
INSERT INTO CityInfo VALUES ('4480','Store Fuglede');
INSERT INTO CityInfo VALUES ('4490','Jerslev Sjælland');
INSERT INTO CityInfo VALUES ('4500','Nykøbing Sj');
INSERT INTO CityInfo VALUES ('4520','Svinninge');
INSERT INTO CityInfo VALUES ('4532','Gislinge');
INSERT INTO CityInfo VALUES ('4534','Hørve');
INSERT INTO CityInfo VALUES ('4540','Fårevejle');
INSERT INTO CityInfo VALUES ('4550','Asnæs');
INSERT INTO CityInfo VALUES ('4560','Vig');
INSERT INTO CityInfo VALUES ('4571','Grevinge');
INSERT INTO CityInfo VALUES ('4572','Nørre Asmindrup');
INSERT INTO CityInfo VALUES ('4573','Højby');
INSERT INTO CityInfo VALUES ('4581','Rørvig');
INSERT INTO CityInfo VALUES ('4583','Sjællands Odde');
INSERT INTO CityInfo VALUES ('4591','Føllenslev');
INSERT INTO CityInfo VALUES ('4592','Sejerø');
INSERT INTO CityInfo VALUES ('4593','Eskebjerg');
INSERT INTO CityInfo VALUES ('4600','Køge');
INSERT INTO CityInfo VALUES ('4621','Gadstrup');
INSERT INTO CityInfo VALUES ('4622','Havdrup');
INSERT INTO CityInfo VALUES ('4623','Lille Skensved');
INSERT INTO CityInfo VALUES ('4632','Bjæverskov');
INSERT INTO CityInfo VALUES ('4640','Faxe');
INSERT INTO CityInfo VALUES ('4652','Hårlev');
INSERT INTO CityInfo VALUES ('4653','Karise');
INSERT INTO CityInfo VALUES ('4654','Faxe Ladeplads');
INSERT INTO CityInfo VALUES ('4660','Store Heddinge');
INSERT INTO CityInfo VALUES ('4671','Strøby');
INSERT INTO CityInfo VALUES ('4672','Klippinge');
INSERT INTO CityInfo VALUES ('4673','Rødvig Stevns');
INSERT INTO CityInfo VALUES ('4681','Herfølge');
INSERT INTO CityInfo VALUES ('4682','Tureby');
INSERT INTO CityInfo VALUES ('4683','Rønnede');
INSERT INTO CityInfo VALUES ('4684','Holmegaard');
INSERT INTO CityInfo VALUES ('4690','Haslev');
INSERT INTO CityInfo VALUES ('4700','Næstved');
INSERT INTO CityInfo VALUES ('4720','Præstø');
INSERT INTO CityInfo VALUES ('4733','Tappernøje');
INSERT INTO CityInfo VALUES ('4735','Mern');
INSERT INTO CityInfo VALUES ('4736','Karrebæksminde');
INSERT INTO CityInfo VALUES ('4750','Lundby');
INSERT INTO CityInfo VALUES ('4760','Vordingborg');
INSERT INTO CityInfo VALUES ('4771','Kalvehave');
INSERT INTO CityInfo VALUES ('4772','Langebæk');
INSERT INTO CityInfo VALUES ('4773','Stensved');
INSERT INTO CityInfo VALUES ('4780','Stege');
INSERT INTO CityInfo VALUES ('4791','Borre');
INSERT INTO CityInfo VALUES ('4792','Askeby');
INSERT INTO CityInfo VALUES ('4793','Bogø By');
INSERT INTO CityInfo VALUES ('4800','Nykøbing F');
INSERT INTO CityInfo VALUES ('4840','Nørre Alslev');
INSERT INTO CityInfo VALUES ('4850','Stubbekøbing');
INSERT INTO CityInfo VALUES ('4862','Guldborg');
INSERT INTO CityInfo VALUES ('4863','Eskilstrup');
INSERT INTO CityInfo VALUES ('4871','Horbelev');
INSERT INTO CityInfo VALUES ('4872','Idestrup');
INSERT INTO CityInfo VALUES ('4873','Væggerløse');
INSERT INTO CityInfo VALUES ('4874','Gedser');
INSERT INTO CityInfo VALUES ('4880','Nysted');
INSERT INTO CityInfo VALUES ('4891','Toreby L');
INSERT INTO CityInfo VALUES ('4892','Kettinge');
INSERT INTO CityInfo VALUES ('4894','Øster Ulslev');
INSERT INTO CityInfo VALUES ('4895','Errindlev');
INSERT INTO CityInfo VALUES ('4900','Nakskov');
INSERT INTO CityInfo VALUES ('4912','Harpelunde');
INSERT INTO CityInfo VALUES ('4913','Horslunde');
INSERT INTO CityInfo VALUES ('4920','Søllested');
INSERT INTO CityInfo VALUES ('4930','Maribo');
INSERT INTO CityInfo VALUES ('4941','Bandholm');
INSERT INTO CityInfo VALUES ('4943','Torrig L');
INSERT INTO CityInfo VALUES ('4944','Fejø');
INSERT INTO CityInfo VALUES ('4951','Nørreballe');
INSERT INTO CityInfo VALUES ('4952','Stokkemarke');
INSERT INTO CityInfo VALUES ('4953','Vesterborg');
INSERT INTO CityInfo VALUES ('4960','Holeby');
INSERT INTO CityInfo VALUES ('4970','Rødby');
INSERT INTO CityInfo VALUES ('4983','Dannemare');
INSERT INTO CityInfo VALUES ('4990','Sakskøbing');
INSERT INTO CityInfo VALUES ('4992','Midtsjælland USF P');
INSERT INTO CityInfo VALUES ('5000','Odense C');
INSERT INTO CityInfo VALUES ('5029','Odense C');
INSERT INTO CityInfo VALUES ('5100','Odense C');
INSERT INTO CityInfo VALUES ('5200','Odense V');
INSERT INTO CityInfo VALUES ('5210','Odense NV');
INSERT INTO CityInfo VALUES ('5220','Odense SØ');
INSERT INTO CityInfo VALUES ('5230','Odense M');
INSERT INTO CityInfo VALUES ('5240','Odense NØ');
INSERT INTO CityInfo VALUES ('5250','Odense SV');
INSERT INTO CityInfo VALUES ('5260','Odense S');
INSERT INTO CityInfo VALUES ('5270','Odense N');
INSERT INTO CityInfo VALUES ('5290','Marslev');
INSERT INTO CityInfo VALUES ('5300','Kerteminde');
INSERT INTO CityInfo VALUES ('5320','Agedrup');
INSERT INTO CityInfo VALUES ('5330','Munkebo');
INSERT INTO CityInfo VALUES ('5350','Rynkeby');
INSERT INTO CityInfo VALUES ('5370','Mesinge');
INSERT INTO CityInfo VALUES ('5380','Dalby');
INSERT INTO CityInfo VALUES ('5390','Martofte');
INSERT INTO CityInfo VALUES ('5400','Bogense');
INSERT INTO CityInfo VALUES ('5450','Otterup');
INSERT INTO CityInfo VALUES ('5462','Morud');
INSERT INTO CityInfo VALUES ('5463','Harndrup');
INSERT INTO CityInfo VALUES ('5464','Brenderup Fyn');
INSERT INTO CityInfo VALUES ('5466','Asperup');
INSERT INTO CityInfo VALUES ('5471','Søndersø');
INSERT INTO CityInfo VALUES ('5474','Veflinge');
INSERT INTO CityInfo VALUES ('5485','Skamby');
INSERT INTO CityInfo VALUES ('5491','Blommenslyst');
INSERT INTO CityInfo VALUES ('5492','Vissenbjerg');
INSERT INTO CityInfo VALUES ('5500','Middelfart');
INSERT INTO CityInfo VALUES ('5540','Ullerslev');
INSERT INTO CityInfo VALUES ('5550','Langeskov');
INSERT INTO CityInfo VALUES ('5560','Aarup');
INSERT INTO CityInfo VALUES ('5580','Nørre Aaby');
INSERT INTO CityInfo VALUES ('5591','Gelsted');
INSERT INTO CityInfo VALUES ('5592','Ejby');
INSERT INTO CityInfo VALUES ('5600','Faaborg');
INSERT INTO CityInfo VALUES ('5610','Assens');
INSERT INTO CityInfo VALUES ('5620','Glamsbjerg');
INSERT INTO CityInfo VALUES ('5631','Ebberup');
INSERT INTO CityInfo VALUES ('5642','Millinge');
INSERT INTO CityInfo VALUES ('5672','Broby');
INSERT INTO CityInfo VALUES ('5683','Haarby');
INSERT INTO CityInfo VALUES ('5690','Tommerup');
INSERT INTO CityInfo VALUES ('5700','Svendborg');
INSERT INTO CityInfo VALUES ('5750','Ringe');
INSERT INTO CityInfo VALUES ('5762','Vester Skerninge');
INSERT INTO CityInfo VALUES ('5771','Stenstrup');
INSERT INTO CityInfo VALUES ('5772','Kværndrup');
INSERT INTO CityInfo VALUES ('5792','Årslev');
INSERT INTO CityInfo VALUES ('5800','Nyborg');
INSERT INTO CityInfo VALUES ('5853','Ørbæk');
INSERT INTO CityInfo VALUES ('5854','Gislev');
INSERT INTO CityInfo VALUES ('5856','Ryslinge');
INSERT INTO CityInfo VALUES ('5863','Ferritslev Fyn');
INSERT INTO CityInfo VALUES ('5871','Frørup');
INSERT INTO CityInfo VALUES ('5874','Hesselager');
INSERT INTO CityInfo VALUES ('5881','Skårup Fyn');
INSERT INTO CityInfo VALUES ('5882','Vejstrup');
INSERT INTO CityInfo VALUES ('5883','Oure');
INSERT INTO CityInfo VALUES ('5884','Gudme');
INSERT INTO CityInfo VALUES ('5892','Gudbjerg Sydfyn');
INSERT INTO CityInfo VALUES ('5900','Rudkøbing');
INSERT INTO CityInfo VALUES ('5932','Humble');
INSERT INTO CityInfo VALUES ('5935','Bagenkop');
INSERT INTO CityInfo VALUES ('5953','Tranekær');
INSERT INTO CityInfo VALUES ('5960','Marstal');
INSERT INTO CityInfo VALUES ('5970','Ærøskøbing');
INSERT INTO CityInfo VALUES ('5985','Søby Ærø');
INSERT INTO CityInfo VALUES ('6000','Kolding');
INSERT INTO CityInfo VALUES ('6040','Egtved');
INSERT INTO CityInfo VALUES ('6051','Almind');
INSERT INTO CityInfo VALUES ('6052','Viuf');
INSERT INTO CityInfo VALUES ('6064','Jordrup');
INSERT INTO CityInfo VALUES ('6070','Christiansfeld');
INSERT INTO CityInfo VALUES ('6091','Bjert');
INSERT INTO CityInfo VALUES ('6092','Sønder Stenderup');
INSERT INTO CityInfo VALUES ('6093','Sjølund');
INSERT INTO CityInfo VALUES ('6094','Hejls');
INSERT INTO CityInfo VALUES ('6100','Haderslev');
INSERT INTO CityInfo VALUES ('6200','Aabenraa');
INSERT INTO CityInfo VALUES ('6230','Rødekro');
INSERT INTO CityInfo VALUES ('6240','Løgumkloster');
INSERT INTO CityInfo VALUES ('6261','Bredebro');
INSERT INTO CityInfo VALUES ('6270','Tønder');
INSERT INTO CityInfo VALUES ('6280','Højer');
INSERT INTO CityInfo VALUES ('6300','Gråsten');
INSERT INTO CityInfo VALUES ('6310','Broager');
INSERT INTO CityInfo VALUES ('6320','Egernsund');
INSERT INTO CityInfo VALUES ('6330','Padborg');
INSERT INTO CityInfo VALUES ('6340','Kruså');
INSERT INTO CityInfo VALUES ('6360','Tinglev');
INSERT INTO CityInfo VALUES ('6372','Bylderup-Bov');
INSERT INTO CityInfo VALUES ('6392','Bolderslev');
INSERT INTO CityInfo VALUES ('6400','Sønderborg');
INSERT INTO CityInfo VALUES ('6430','Nordborg');
INSERT INTO CityInfo VALUES ('6440','Augustenborg');
INSERT INTO CityInfo VALUES ('6470','Sydals');
INSERT INTO CityInfo VALUES ('6500','Vojens');
INSERT INTO CityInfo VALUES ('6510','Gram');
INSERT INTO CityInfo VALUES ('6520','Toftlund');
INSERT INTO CityInfo VALUES ('6534','Agerskov');
INSERT INTO CityInfo VALUES ('6535','Branderup J');
INSERT INTO CityInfo VALUES ('6541','Bevtoft');
INSERT INTO CityInfo VALUES ('6560','Sommersted');
INSERT INTO CityInfo VALUES ('6580','Vamdrup');
INSERT INTO CityInfo VALUES ('6600','Vejen');
INSERT INTO CityInfo VALUES ('6621','Gesten');
INSERT INTO CityInfo VALUES ('6622','Bække');
INSERT INTO CityInfo VALUES ('6623','Vorbasse');
INSERT INTO CityInfo VALUES ('6630','Rødding');
INSERT INTO CityInfo VALUES ('6640','Lunderskov');
INSERT INTO CityInfo VALUES ('6650','Brørup');
INSERT INTO CityInfo VALUES ('6660','Lintrup');
INSERT INTO CityInfo VALUES ('6670','Holsted');
INSERT INTO CityInfo VALUES ('6682','Hovborg');
INSERT INTO CityInfo VALUES ('6683','Føvling');
INSERT INTO CityInfo VALUES ('6690','Gørding');
INSERT INTO CityInfo VALUES ('6700','Esbjerg');
INSERT INTO CityInfo VALUES ('6701','Esbjerg');
INSERT INTO CityInfo VALUES ('6705','Esbjerg Ø');
INSERT INTO CityInfo VALUES ('6710','Esbjerg V');
INSERT INTO CityInfo VALUES ('6715','Esbjerg N');
INSERT INTO CityInfo VALUES ('6720','Fanø');
INSERT INTO CityInfo VALUES ('6731','Tjæreborg');
INSERT INTO CityInfo VALUES ('6740','Bramming');
INSERT INTO CityInfo VALUES ('6752','Glejbjerg');
INSERT INTO CityInfo VALUES ('6753','Agerbæk');
INSERT INTO CityInfo VALUES ('6760','Ribe');
INSERT INTO CityInfo VALUES ('6771','Gredstedbro');
INSERT INTO CityInfo VALUES ('6780','Skærbæk');
INSERT INTO CityInfo VALUES ('6792','Rømø');
INSERT INTO CityInfo VALUES ('6800','Varde');
INSERT INTO CityInfo VALUES ('6818','Årre');
INSERT INTO CityInfo VALUES ('6823','Ansager');
INSERT INTO CityInfo VALUES ('6830','Nørre Nebel');
INSERT INTO CityInfo VALUES ('6840','Oksbøl');
INSERT INTO CityInfo VALUES ('6851','Janderup Vestj');
INSERT INTO CityInfo VALUES ('6852','Billum');
INSERT INTO CityInfo VALUES ('6853','Vejers Strand');
INSERT INTO CityInfo VALUES ('6854','Henne');
INSERT INTO CityInfo VALUES ('6855','Outrup');
INSERT INTO CityInfo VALUES ('6857','Blåvand');
INSERT INTO CityInfo VALUES ('6862','Tistrup');
INSERT INTO CityInfo VALUES ('6870','Ølgod');
INSERT INTO CityInfo VALUES ('6880','Tarm');
INSERT INTO CityInfo VALUES ('6893','Hemmet');
INSERT INTO CityInfo VALUES ('6900','Skjern');
INSERT INTO CityInfo VALUES ('6920','Videbæk');
INSERT INTO CityInfo VALUES ('6933','Kibæk');
INSERT INTO CityInfo VALUES ('6940','Lem St');
INSERT INTO CityInfo VALUES ('6950','Ringkøbing');
INSERT INTO CityInfo VALUES ('6960','Hvide Sande');
INSERT INTO CityInfo VALUES ('6971','Spjald');
INSERT INTO CityInfo VALUES ('6973','Ørnhøj');
INSERT INTO CityInfo VALUES ('6980','Tim');
INSERT INTO CityInfo VALUES ('6990','Ulfborg');
INSERT INTO CityInfo VALUES ('7000','Fredericia');
INSERT INTO CityInfo VALUES ('7007','Fredericia');
INSERT INTO CityInfo VALUES ('7017','Taulov Pakkecenter');
INSERT INTO CityInfo VALUES ('7018','Pakker TLP');
INSERT INTO CityInfo VALUES ('7029','Fredericia');
INSERT INTO CityInfo VALUES ('7080','Børkop');
INSERT INTO CityInfo VALUES ('7100','Vejle');
INSERT INTO CityInfo VALUES ('7120','Vejle Øst');
INSERT INTO CityInfo VALUES ('7130','Juelsminde');
INSERT INTO CityInfo VALUES ('7140','Stouby');
INSERT INTO CityInfo VALUES ('7150','Barrit');
INSERT INTO CityInfo VALUES ('7160','Tørring');
INSERT INTO CityInfo VALUES ('7171','Uldum');
INSERT INTO CityInfo VALUES ('7173','Vonge');
INSERT INTO CityInfo VALUES ('7182','Bredsten');
INSERT INTO CityInfo VALUES ('7183','Randbøl');
INSERT INTO CityInfo VALUES ('7184','Vandel');
INSERT INTO CityInfo VALUES ('7190','Billund');
INSERT INTO CityInfo VALUES ('7200','Grindsted');
INSERT INTO CityInfo VALUES ('7250','Hejnsvig');
INSERT INTO CityInfo VALUES ('7260','Sønder Omme');
INSERT INTO CityInfo VALUES ('7270','Stakroge');
INSERT INTO CityInfo VALUES ('7280','Sønder Felding');
INSERT INTO CityInfo VALUES ('7300','Jelling');
INSERT INTO CityInfo VALUES ('7321','Gadbjerg');
INSERT INTO CityInfo VALUES ('7323','Give');
INSERT INTO CityInfo VALUES ('7330','Brande');
INSERT INTO CityInfo VALUES ('7361','Ejstrupholm');
INSERT INTO CityInfo VALUES ('7362','Hampen');
INSERT INTO CityInfo VALUES ('7400','Herning');
INSERT INTO CityInfo VALUES ('7429','Herning');
INSERT INTO CityInfo VALUES ('7430','Ikast');
INSERT INTO CityInfo VALUES ('7441','Bording');
INSERT INTO CityInfo VALUES ('7442','Engesvang');
INSERT INTO CityInfo VALUES ('7451','Sunds');
INSERT INTO CityInfo VALUES ('7470','Karup J');
INSERT INTO CityInfo VALUES ('7480','Vildbjerg');
INSERT INTO CityInfo VALUES ('7490','Aulum');
INSERT INTO CityInfo VALUES ('7500','Holstebro');
INSERT INTO CityInfo VALUES ('7540','Haderup');
INSERT INTO CityInfo VALUES ('7550','Sørvad');
INSERT INTO CityInfo VALUES ('7560','Hjerm');
INSERT INTO CityInfo VALUES ('7570','Vemb');
INSERT INTO CityInfo VALUES ('7600','Struer');
INSERT INTO CityInfo VALUES ('7620','Lemvig');
INSERT INTO CityInfo VALUES ('7650','Bøvlingbjerg');
INSERT INTO CityInfo VALUES ('7660','Bækmarksbro');
INSERT INTO CityInfo VALUES ('7673','Harboøre');
INSERT INTO CityInfo VALUES ('7680','Thyborøn');
INSERT INTO CityInfo VALUES ('7700','Thisted');
INSERT INTO CityInfo VALUES ('7730','Hanstholm');
INSERT INTO CityInfo VALUES ('7741','Frøstrup');
INSERT INTO CityInfo VALUES ('7742','Vesløs');
INSERT INTO CityInfo VALUES ('7752','Snedsted');
INSERT INTO CityInfo VALUES ('7755','Bedsted Thy');
INSERT INTO CityInfo VALUES ('7760','Hurup Thy');
INSERT INTO CityInfo VALUES ('7770','Vestervig');
INSERT INTO CityInfo VALUES ('7790','Thyholm');
INSERT INTO CityInfo VALUES ('7800','Skive');
INSERT INTO CityInfo VALUES ('7830','Vinderup');
INSERT INTO CityInfo VALUES ('7840','Højslev');
INSERT INTO CityInfo VALUES ('7850','Stoholm Jyll');
INSERT INTO CityInfo VALUES ('7860','Spøttrup');
INSERT INTO CityInfo VALUES ('7870','Roslev');
INSERT INTO CityInfo VALUES ('7884','Fur');
INSERT INTO CityInfo VALUES ('7900','Nykøbing M');
INSERT INTO CityInfo VALUES ('7950','Erslev');
INSERT INTO CityInfo VALUES ('7960','Karby');
INSERT INTO CityInfo VALUES ('7970','Redsted M');
INSERT INTO CityInfo VALUES ('7980','Vils');
INSERT INTO CityInfo VALUES ('7990','Øster Assels');
INSERT INTO CityInfo VALUES ('7992','Sydjylland/Fyn USF P');
INSERT INTO CityInfo VALUES ('7993','Sydjylland/Fyn USF B');
INSERT INTO CityInfo VALUES ('7996','Fakturaservice');
INSERT INTO CityInfo VALUES ('7997','Fakturascanning');
INSERT INTO CityInfo VALUES ('7998','Statsservice');
INSERT INTO CityInfo VALUES ('7999','Kommunepost');
INSERT INTO CityInfo VALUES ('8000','Aarhus C');
INSERT INTO CityInfo VALUES ('8100','Aarhus C');
INSERT INTO CityInfo VALUES ('8200','Aarhus N');
INSERT INTO CityInfo VALUES ('8210','Aarhus V');
INSERT INTO CityInfo VALUES ('8220','Brabrand');
INSERT INTO CityInfo VALUES ('8229','Risskov Ø');
INSERT INTO CityInfo VALUES ('8230','Åbyhøj');
INSERT INTO CityInfo VALUES ('8240','Risskov');
INSERT INTO CityInfo VALUES ('8245','Risskov Ø');
INSERT INTO CityInfo VALUES ('8250','Egå');
INSERT INTO CityInfo VALUES ('8260','Viby J');
INSERT INTO CityInfo VALUES ('8270','Højbjerg');
INSERT INTO CityInfo VALUES ('8300','Odder');
INSERT INTO CityInfo VALUES ('8305','Samsø');
INSERT INTO CityInfo VALUES ('8310','Tranbjerg J');
INSERT INTO CityInfo VALUES ('8320','Mårslet');
INSERT INTO CityInfo VALUES ('8330','Beder');
INSERT INTO CityInfo VALUES ('8340','Malling');
INSERT INTO CityInfo VALUES ('8350','Hundslund');
INSERT INTO CityInfo VALUES ('8355','Solbjerg');
INSERT INTO CityInfo VALUES ('8361','Hasselager');
INSERT INTO CityInfo VALUES ('8362','Hørning');
INSERT INTO CityInfo VALUES ('8370','Hadsten');
INSERT INTO CityInfo VALUES ('8380','Trige');
INSERT INTO CityInfo VALUES ('8381','Tilst');
INSERT INTO CityInfo VALUES ('8382','Hinnerup');
INSERT INTO CityInfo VALUES ('8400','Ebeltoft');
INSERT INTO CityInfo VALUES ('8410','Rønde');
INSERT INTO CityInfo VALUES ('8420','Knebel');
INSERT INTO CityInfo VALUES ('8444','Balle');
INSERT INTO CityInfo VALUES ('8450','Hammel');
INSERT INTO CityInfo VALUES ('8462','Harlev J');
INSERT INTO CityInfo VALUES ('8464','Galten');
INSERT INTO CityInfo VALUES ('8471','Sabro');
INSERT INTO CityInfo VALUES ('8472','Sporup');
INSERT INTO CityInfo VALUES ('8500','Grenaa');
INSERT INTO CityInfo VALUES ('8520','Lystrup');
INSERT INTO CityInfo VALUES ('8530','Hjortshøj');
INSERT INTO CityInfo VALUES ('8541','Skødstrup');
INSERT INTO CityInfo VALUES ('8543','Hornslet');
INSERT INTO CityInfo VALUES ('8544','Mørke');
INSERT INTO CityInfo VALUES ('8550','Ryomgård');
INSERT INTO CityInfo VALUES ('8560','Kolind');
INSERT INTO CityInfo VALUES ('8570','Trustrup');
INSERT INTO CityInfo VALUES ('8581','Nimtofte');
INSERT INTO CityInfo VALUES ('8585','Glesborg');
INSERT INTO CityInfo VALUES ('8586','Ørum Djurs');
INSERT INTO CityInfo VALUES ('8592','Anholt');
INSERT INTO CityInfo VALUES ('8600','Silkeborg');
INSERT INTO CityInfo VALUES ('8620','Kjellerup');
INSERT INTO CityInfo VALUES ('8632','Lemming');
INSERT INTO CityInfo VALUES ('8641','Sorring');
INSERT INTO CityInfo VALUES ('8643','Ans By');
INSERT INTO CityInfo VALUES ('8653','Them');
INSERT INTO CityInfo VALUES ('8654','Bryrup');
INSERT INTO CityInfo VALUES ('8660','Skanderborg');
INSERT INTO CityInfo VALUES ('8670','Låsby');
INSERT INTO CityInfo VALUES ('8680','Ry');
INSERT INTO CityInfo VALUES ('8700','Horsens');
INSERT INTO CityInfo VALUES ('8721','Daugård');
INSERT INTO CityInfo VALUES ('8722','Hedensted');
INSERT INTO CityInfo VALUES ('8723','Løsning');
INSERT INTO CityInfo VALUES ('8732','Hovedgård');
INSERT INTO CityInfo VALUES ('8740','Brædstrup');
INSERT INTO CityInfo VALUES ('8751','Gedved');
INSERT INTO CityInfo VALUES ('8752','Østbirk');
INSERT INTO CityInfo VALUES ('8762','Flemming');
INSERT INTO CityInfo VALUES ('8763','Rask Mølle');
INSERT INTO CityInfo VALUES ('8765','Klovborg');
INSERT INTO CityInfo VALUES ('8766','Nørre Snede');
INSERT INTO CityInfo VALUES ('8781','Stenderup');
INSERT INTO CityInfo VALUES ('8783','Hornsyld');
INSERT INTO CityInfo VALUES ('8800','Viborg');
INSERT INTO CityInfo VALUES ('8830','Tjele');
INSERT INTO CityInfo VALUES ('8831','Løgstrup');
INSERT INTO CityInfo VALUES ('8832','Skals');
INSERT INTO CityInfo VALUES ('8840','Rødkærsbro');
INSERT INTO CityInfo VALUES ('8850','Bjerringbro');
INSERT INTO CityInfo VALUES ('8860','Ulstrup');
INSERT INTO CityInfo VALUES ('8870','Langå');
INSERT INTO CityInfo VALUES ('8881','Thorsø');
INSERT INTO CityInfo VALUES ('8882','Fårvang');
INSERT INTO CityInfo VALUES ('8883','Gjern');
INSERT INTO CityInfo VALUES ('8900','Randers C');
INSERT INTO CityInfo VALUES ('8920','Randers NV');
INSERT INTO CityInfo VALUES ('8930','Randers NØ');
INSERT INTO CityInfo VALUES ('8940','Randers SV');
INSERT INTO CityInfo VALUES ('8950','Ørsted');
INSERT INTO CityInfo VALUES ('8960','Randers SØ');
INSERT INTO CityInfo VALUES ('8961','Allingåbro');
INSERT INTO CityInfo VALUES ('8963','Auning');
INSERT INTO CityInfo VALUES ('8970','Havndal');
INSERT INTO CityInfo VALUES ('8981','Spentrup');
INSERT INTO CityInfo VALUES ('8983','Gjerlev J');
INSERT INTO CityInfo VALUES ('8990','Fårup');
INSERT INTO CityInfo VALUES ('9000','Aalborg');
INSERT INTO CityInfo VALUES ('9029','Aalborg');
INSERT INTO CityInfo VALUES ('9100','Aalborg');
INSERT INTO CityInfo VALUES ('9200','Aalborg SV');
INSERT INTO CityInfo VALUES ('9210','Aalborg SØ');
INSERT INTO CityInfo VALUES ('9220','Aalborg Øst');
INSERT INTO CityInfo VALUES ('9230','Svenstrup J');
INSERT INTO CityInfo VALUES ('9240','Nibe');
INSERT INTO CityInfo VALUES ('9260','Gistrup');
INSERT INTO CityInfo VALUES ('9270','Klarup');
INSERT INTO CityInfo VALUES ('9280','Storvorde');
INSERT INTO CityInfo VALUES ('9293','Kongerslev');
INSERT INTO CityInfo VALUES ('9300','Sæby');
INSERT INTO CityInfo VALUES ('9310','Vodskov');
INSERT INTO CityInfo VALUES ('9320','Hjallerup');
INSERT INTO CityInfo VALUES ('9330','Dronninglund');
INSERT INTO CityInfo VALUES ('9340','Asaa');
INSERT INTO CityInfo VALUES ('9352','Dybvad');
INSERT INTO CityInfo VALUES ('9362','Gandrup');
INSERT INTO CityInfo VALUES ('9370','Hals');
INSERT INTO CityInfo VALUES ('9380','Vestbjerg');
INSERT INTO CityInfo VALUES ('9381','Sulsted');
INSERT INTO CityInfo VALUES ('9382','Tylstrup');
INSERT INTO CityInfo VALUES ('9400','Nørresundby');
INSERT INTO CityInfo VALUES ('9430','Vadum');
INSERT INTO CityInfo VALUES ('9440','Aabybro');
INSERT INTO CityInfo VALUES ('9460','Brovst');
INSERT INTO CityInfo VALUES ('9480','Løkken');
INSERT INTO CityInfo VALUES ('9490','Pandrup');
INSERT INTO CityInfo VALUES ('9492','Blokhus');
INSERT INTO CityInfo VALUES ('9493','Saltum');
INSERT INTO CityInfo VALUES ('9500','Hobro');
INSERT INTO CityInfo VALUES ('9510','Arden');
INSERT INTO CityInfo VALUES ('9520','Skørping');
INSERT INTO CityInfo VALUES ('9530','Støvring');
INSERT INTO CityInfo VALUES ('9541','Suldrup');
INSERT INTO CityInfo VALUES ('9550','Mariager');
INSERT INTO CityInfo VALUES ('9560','Hadsund');
INSERT INTO CityInfo VALUES ('9574','Bælum');
INSERT INTO CityInfo VALUES ('9575','Terndrup');
INSERT INTO CityInfo VALUES ('9600','Aars');
INSERT INTO CityInfo VALUES ('9610','Nørager');
INSERT INTO CityInfo VALUES ('9620','Aalestrup');
INSERT INTO CityInfo VALUES ('9631','Gedsted');
INSERT INTO CityInfo VALUES ('9632','Møldrup');
INSERT INTO CityInfo VALUES ('9640','Farsø');
INSERT INTO CityInfo VALUES ('9670','Løgstør');
INSERT INTO CityInfo VALUES ('9681','Ranum');
INSERT INTO CityInfo VALUES ('9690','Fjerritslev');
INSERT INTO CityInfo VALUES ('9700','Brønderslev');
INSERT INTO CityInfo VALUES ('9740','Jerslev J');
INSERT INTO CityInfo VALUES ('9750','Østervrå');
INSERT INTO CityInfo VALUES ('9760','Vrå');
INSERT INTO CityInfo VALUES ('9800','Hjørring');
INSERT INTO CityInfo VALUES ('9830','Tårs');
INSERT INTO CityInfo VALUES ('9850','Hirtshals');
INSERT INTO CityInfo VALUES ('9870','Sindal');
INSERT INTO CityInfo VALUES ('9881','Bindslev');
INSERT INTO CityInfo VALUES ('9900','Frederikshavn');
INSERT INTO CityInfo VALUES ('9940','Læsø');
INSERT INTO CityInfo VALUES ('9970','Strandby');
INSERT INTO CityInfo VALUES ('9981','Jerup');
INSERT INTO CityInfo VALUES ('9982','Ålbæk');
INSERT INTO CityInfo VALUES ('9990','Skagen');
INSERT INTO CityInfo VALUES ('9992','Jylland USF P');
INSERT INTO CityInfo VALUES ('9993','Jylland USF B');
INSERT INTO CityInfo VALUES ('9996','Fakturaservice');
INSERT INTO CityInfo VALUES ('9997','Fakturascanning');
INSERT INTO CityInfo VALUES ('9998','Borgerservice');
INSERT INTO CityInfo VALUES ('2412','Santa Claus/Julemanden');
INSERT INTO CityInfo VALUES ('3900','Nuuk');
INSERT INTO CityInfo VALUES ('3905','Nuussuaq');
INSERT INTO CityInfo VALUES ('3910','Kangerlussuaq');
INSERT INTO CityInfo VALUES ('3911','Sisimiut');
INSERT INTO CityInfo VALUES ('3912','Maniitsoq');
INSERT INTO CityInfo VALUES ('3913','Tasiilaq');
INSERT INTO CityInfo VALUES ('3915','Kulusuk');
INSERT INTO CityInfo VALUES ('3919','Alluitsup Paa');
INSERT INTO CityInfo VALUES ('3920','Qaqortoq');
INSERT INTO CityInfo VALUES ('3921','Narsaq');
INSERT INTO CityInfo VALUES ('3922','Nanortalik');
INSERT INTO CityInfo VALUES ('3923','Narsarsuaq');
INSERT INTO CityInfo VALUES ('3924','Ikerasassuaq');
INSERT INTO CityInfo VALUES ('3930','Kangilinnguit');
INSERT INTO CityInfo VALUES ('3932','Arsuk');
INSERT INTO CityInfo VALUES ('3940','Paamiut');
INSERT INTO CityInfo VALUES ('3950','Aasiaat');
INSERT INTO CityInfo VALUES ('3951','Qasigiannguit');
INSERT INTO CityInfo VALUES ('3952','Ilulissat');
INSERT INTO CityInfo VALUES ('3953','Qeqertarsuaq');
INSERT INTO CityInfo VALUES ('3955','Kangaatsiaq');
INSERT INTO CityInfo VALUES ('3961','Uummannaq');
INSERT INTO CityInfo VALUES ('3962','Upernavik');
INSERT INTO CityInfo VALUES ('3964','Qaarsut');
INSERT INTO CityInfo VALUES ('3970','Pituffik');
INSERT INTO CityInfo VALUES ('3971','Qaanaaq');
INSERT INTO CityInfo VALUES ('3972','Station Nord');
INSERT INTO CityInfo VALUES ('3980','Ittoqqortoormiit');
INSERT INTO CityInfo VALUES ('3982','Mestersvig');
INSERT INTO CityInfo VALUES ('3984','Danmarkshavn');
INSERT INTO CityInfo VALUES ('3985','Constable Pynt');
INSERT INTO CityInfo VALUES ('3992','Slædepatrulje Sirius');
INSERT INTO CityInfo VALUES ('100','Tórshavn');
INSERT INTO CityInfo VALUES ('110','Tórshavn ');
INSERT INTO CityInfo VALUES ('160','Argir');
INSERT INTO CityInfo VALUES ('165','Argir ');
INSERT INTO CityInfo VALUES ('175','Kirkjubøur');
INSERT INTO CityInfo VALUES ('176','Velbastadur');
INSERT INTO CityInfo VALUES ('177','Sydradalur, Streymoy');
INSERT INTO CityInfo VALUES ('178','Nordradalur');
INSERT INTO CityInfo VALUES ('180','Kaldbak');
INSERT INTO CityInfo VALUES ('185','Kaldbaksbotnur');
INSERT INTO CityInfo VALUES ('186','Sund');
INSERT INTO CityInfo VALUES ('187','Hvitanes');
INSERT INTO CityInfo VALUES ('188','Hoyvík');
INSERT INTO CityInfo VALUES ('210','Sandur');
INSERT INTO CityInfo VALUES ('215','Sandur');
INSERT INTO CityInfo VALUES ('220','Skálavík');
INSERT INTO CityInfo VALUES ('230','Húsavík');
INSERT INTO CityInfo VALUES ('235','Dalur');
INSERT INTO CityInfo VALUES ('236','Skarvanes');
INSERT INTO CityInfo VALUES ('240','Skopun');
INSERT INTO CityInfo VALUES ('260','Skúvoy');
INSERT INTO CityInfo VALUES ('270','Nólsoy');
INSERT INTO CityInfo VALUES ('280','Hestur');
INSERT INTO CityInfo VALUES ('285','Koltur');
INSERT INTO CityInfo VALUES ('286','Stóra Dimun');
INSERT INTO CityInfo VALUES ('330','Stykkid');
INSERT INTO CityInfo VALUES ('335','Leynar');
INSERT INTO CityInfo VALUES ('336','Skællingur');
INSERT INTO CityInfo VALUES ('340','Kvívík');
INSERT INTO CityInfo VALUES ('350','Vestmanna');
INSERT INTO CityInfo VALUES ('355','Vestmanna');
INSERT INTO CityInfo VALUES ('358','Válur');
INSERT INTO CityInfo VALUES ('360','Sandavágur');
INSERT INTO CityInfo VALUES ('370','Midvágur');
INSERT INTO CityInfo VALUES ('375','Midvágur');
INSERT INTO CityInfo VALUES ('380','Sørvágur');
INSERT INTO CityInfo VALUES ('385','Vatnsoyrar');
INSERT INTO CityInfo VALUES ('386','Bøur');
INSERT INTO CityInfo VALUES ('387','Gásadalur');
INSERT INTO CityInfo VALUES ('388','Mykines');
INSERT INTO CityInfo VALUES ('400','Oyrarbakki');
INSERT INTO CityInfo VALUES ('405','Oyrarbakki');
INSERT INTO CityInfo VALUES ('410','Kollafjørdur');
INSERT INTO CityInfo VALUES ('415','Oyrareingir');
INSERT INTO CityInfo VALUES ('416','Signabøur');
INSERT INTO CityInfo VALUES ('420','Hósvík');
INSERT INTO CityInfo VALUES ('430','Hvalvík');
INSERT INTO CityInfo VALUES ('435','Streymnes');
INSERT INTO CityInfo VALUES ('436','Saksun');
INSERT INTO CityInfo VALUES ('437','Nesvík');
INSERT INTO CityInfo VALUES ('438','Langasandur');
INSERT INTO CityInfo VALUES ('440','Haldarsvík');
INSERT INTO CityInfo VALUES ('445','Tjørnuvík');
INSERT INTO CityInfo VALUES ('450','Oyri');
INSERT INTO CityInfo VALUES ('460','Nordskáli');
INSERT INTO CityInfo VALUES ('465','Svináir');
INSERT INTO CityInfo VALUES ('466','Ljósá');
INSERT INTO CityInfo VALUES ('470','Eidi');
INSERT INTO CityInfo VALUES ('475','Funningur');
INSERT INTO CityInfo VALUES ('476','Gjógv');
INSERT INTO CityInfo VALUES ('477','Funningsfjørdur');
INSERT INTO CityInfo VALUES ('478','Elduvík');
INSERT INTO CityInfo VALUES ('480','Skáli');
INSERT INTO CityInfo VALUES ('485','Skálafjørdur');
INSERT INTO CityInfo VALUES ('490','Strendur');
INSERT INTO CityInfo VALUES ('494','Innan Glyvur');
INSERT INTO CityInfo VALUES ('495','Kolbanargjógv');
INSERT INTO CityInfo VALUES ('496','Morskranes');
INSERT INTO CityInfo VALUES ('497','Selatrad');
INSERT INTO CityInfo VALUES ('510','Gøta');
INSERT INTO CityInfo VALUES ('511','Gøtugjógv');
INSERT INTO CityInfo VALUES ('512','Nordragøta');
INSERT INTO CityInfo VALUES ('513','Sydrugøta');
INSERT INTO CityInfo VALUES ('515','Gøta');
INSERT INTO CityInfo VALUES ('520','Leirvík');
INSERT INTO CityInfo VALUES ('530','Fuglafjørdur');
INSERT INTO CityInfo VALUES ('535','Fuglafjørdur');
INSERT INTO CityInfo VALUES ('600','Saltangará');
INSERT INTO CityInfo VALUES ('610','Saltangará');
INSERT INTO CityInfo VALUES ('620','Runavík');
INSERT INTO CityInfo VALUES ('625','Glyvrar');
INSERT INTO CityInfo VALUES ('626','Lambareidi');
INSERT INTO CityInfo VALUES ('627','Lambi');
INSERT INTO CityInfo VALUES ('640','Rituvík');
INSERT INTO CityInfo VALUES ('645','Æduvík');
INSERT INTO CityInfo VALUES ('650','Toftir');
INSERT INTO CityInfo VALUES ('655','Nes, Eysturoy');
INSERT INTO CityInfo VALUES ('656','Saltnes');
INSERT INTO CityInfo VALUES ('660','Søldarfjørdur');
INSERT INTO CityInfo VALUES ('665','Skipanes');
INSERT INTO CityInfo VALUES ('666','Gøtueidi');
INSERT INTO CityInfo VALUES ('690','Oyndarfjørdur');
INSERT INTO CityInfo VALUES ('695','Hellur');
INSERT INTO CityInfo VALUES ('700','Klaksvík');
INSERT INTO CityInfo VALUES ('710','Klaksvík');
INSERT INTO CityInfo VALUES ('725','Nordoyri');
INSERT INTO CityInfo VALUES ('726','Ánir');
INSERT INTO CityInfo VALUES ('727','Árnafjørdur');
INSERT INTO CityInfo VALUES ('730','Norddepil');
INSERT INTO CityInfo VALUES ('735','Depil');
INSERT INTO CityInfo VALUES ('736','Nordtoftir');
INSERT INTO CityInfo VALUES ('737','Múli');
INSERT INTO CityInfo VALUES ('740','Hvannasund');
INSERT INTO CityInfo VALUES ('750','Vidareidi');
INSERT INTO CityInfo VALUES ('765','Svinoy');
INSERT INTO CityInfo VALUES ('766','Kirkja');
INSERT INTO CityInfo VALUES ('767','Hattarvík');
INSERT INTO CityInfo VALUES ('780','Kunoy');
INSERT INTO CityInfo VALUES ('785','Haraldssund');
INSERT INTO CityInfo VALUES ('795','Sydradalur, Kalsoy');
INSERT INTO CityInfo VALUES ('796','Húsar');
INSERT INTO CityInfo VALUES ('797','Mikladalur');
INSERT INTO CityInfo VALUES ('798','Trøllanes');
INSERT INTO CityInfo VALUES ('800','Tvøroyri');
INSERT INTO CityInfo VALUES ('810','Tvøroyri');
INSERT INTO CityInfo VALUES ('825','Frodba');
INSERT INTO CityInfo VALUES ('826','Trongisvágur');
INSERT INTO CityInfo VALUES ('827','Øravík');
INSERT INTO CityInfo VALUES ('850','Hvalba');
INSERT INTO CityInfo VALUES ('860','Sandvík');
INSERT INTO CityInfo VALUES ('870','Fámjin');
INSERT INTO CityInfo VALUES ('900','Vágur');
INSERT INTO CityInfo VALUES ('910','Vágur');
INSERT INTO CityInfo VALUES ('925','Nes, Vágur');
INSERT INTO CityInfo VALUES ('926','Lopra');
INSERT INTO CityInfo VALUES ('927','Akrar');
INSERT INTO CityInfo VALUES ('928','Vikarbyrgi');
INSERT INTO CityInfo VALUES ('950','Porkeri');
INSERT INTO CityInfo VALUES ('960','Hov');
INSERT INTO CityInfo VALUES ('970','Sumba');